package vcfs.model;

import java.time.LocalDateTime;

/**
 * Represents a notification sent to a candidate or recruiter.
 * Notifications are generated by the system for events like cancellations.
 */
public class Notification {

    private String id;
    private String message;
    private String recipient;
    private LocalDateTime timestamp;

    public Notification(String id, String message, String recipient) {
        this.id = id;
        this.message = message;
        this.recipient = recipient;
        this.timestamp = LocalDateTime.now();
    }

    /**
     * Sends this notification to the recipient.
     */
    public void send() {
        System.out.println("[Notification] To: " + recipient + " | " + message);
    }

    // Getters
    public String getId() { return id; }
    public String getMessage() { return message; }
    public String getRecipient() { return recipient; }
    public LocalDateTime getTimestamp() { return timestamp; }
}
